name: Update SVG Version
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Increment SVG Version
        id: increment_version
        run: |
          current_version=$(grep -oP '(?<=v=)\d+' README.md)
          echo "Current version: $current_version"
          new_version=$((current_version + 1))
          echo "New version: $new_version"
          sed -i "s/v=$current_version/v=$new_version/" README.md

      - name: Commit Changes
        id: commit
        run: |
          git config --local user.email "weg1456@gmail.com"
          git config --local user.name "weg-9000"
          git add README.md
          # 변경이 있을 때만 커밋
          if ! git diff --cached --quiet; then
            git commit -m "Increment SVG version to v$new_version"
            echo "push=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit."
            echo "push=false" >> $GITHUB_OUTPUT
          fi

      - name: Push Changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.WEG9000PROFILE }}
          branch: main

